require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FakeThingsController do

  # This should return the minimal set of attributes required to create a valid
  # FakeThing. As you add validations to FakeThing, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FakeThingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fake_things as @fake_things" do
      fake_thing = FakeThing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fake_things).should eq([fake_thing])
    end
  end

  describe "GET show" do
    it "assigns the requested fake_thing as @fake_thing" do
      fake_thing = FakeThing.create! valid_attributes
      get :show, {:id => fake_thing.to_param}, valid_session
      assigns(:fake_thing).should eq(fake_thing)
    end
  end

  describe "GET new" do
    it "assigns a new fake_thing as @fake_thing" do
      get :new, {}, valid_session
      assigns(:fake_thing).should be_a_new(FakeThing)
    end
  end

  describe "GET edit" do
    it "assigns the requested fake_thing as @fake_thing" do
      fake_thing = FakeThing.create! valid_attributes
      get :edit, {:id => fake_thing.to_param}, valid_session
      assigns(:fake_thing).should eq(fake_thing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FakeThing" do
        expect {
          post :create, {:fake_thing => valid_attributes}, valid_session
        }.to change(FakeThing, :count).by(1)
      end

      it "assigns a newly created fake_thing as @fake_thing" do
        post :create, {:fake_thing => valid_attributes}, valid_session
        assigns(:fake_thing).should be_a(FakeThing)
        assigns(:fake_thing).should be_persisted
      end

      it "redirects to the created fake_thing" do
        post :create, {:fake_thing => valid_attributes}, valid_session
        response.should redirect_to(FakeThing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fake_thing as @fake_thing" do
        # Trigger the behavior that occurs when invalid params are submitted
        FakeThing.any_instance.stub(:save).and_return(false)
        post :create, {:fake_thing => {}}, valid_session
        assigns(:fake_thing).should be_a_new(FakeThing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FakeThing.any_instance.stub(:save).and_return(false)
        post :create, {:fake_thing => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fake_thing" do
        fake_thing = FakeThing.create! valid_attributes
        # Assuming there are no other fake_things in the database, this
        # specifies that the FakeThing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FakeThing.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => fake_thing.to_param, :fake_thing => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested fake_thing as @fake_thing" do
        fake_thing = FakeThing.create! valid_attributes
        put :update, {:id => fake_thing.to_param, :fake_thing => valid_attributes}, valid_session
        assigns(:fake_thing).should eq(fake_thing)
      end

      it "redirects to the fake_thing" do
        fake_thing = FakeThing.create! valid_attributes
        put :update, {:id => fake_thing.to_param, :fake_thing => valid_attributes}, valid_session
        response.should redirect_to(fake_thing)
      end
    end

    describe "with invalid params" do
      it "assigns the fake_thing as @fake_thing" do
        fake_thing = FakeThing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FakeThing.any_instance.stub(:save).and_return(false)
        put :update, {:id => fake_thing.to_param, :fake_thing => {}}, valid_session
        assigns(:fake_thing).should eq(fake_thing)
      end

      it "re-renders the 'edit' template" do
        fake_thing = FakeThing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FakeThing.any_instance.stub(:save).and_return(false)
        put :update, {:id => fake_thing.to_param, :fake_thing => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fake_thing" do
      fake_thing = FakeThing.create! valid_attributes
      expect {
        delete :destroy, {:id => fake_thing.to_param}, valid_session
      }.to change(FakeThing, :count).by(-1)
    end

    it "redirects to the fake_things list" do
      fake_thing = FakeThing.create! valid_attributes
      delete :destroy, {:id => fake_thing.to_param}, valid_session
      response.should redirect_to(fake_things_url)
    end
  end

end
